# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03c57770152b979d62a2b76ca5c0eac85a0b4536cab83c3e827dd5762ca990912b21e5b4c20ca75bd3450b20939b4d59bb1a70680d572a431356eb989fd8d8a6

test:
  secret_key_base: f52112b802bcb1d91258e5acac3105004518888ba8bf49b861d2ec860452ce3146922d64dcd15e49f6a8981109c734b145a126b3d5a1414faced8a18e01b7904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
